name: Build-with-CMake-on-Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: | 
          mkdir third-party
          mkdir artifacts
          git submodule add https://github.com/google/googletest third-party/gtest
          cd third-party/gtest && git checkout release-1.11.0 && cd ../..
          cmake -B_build

      - name: Build project
        run: cmake --build _build --config Release
