name: Build-with-CMake-on-Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: |
          cmake -B_build
          tree _build
          mkdir artifacts
          mv _build artifacts

      - name: Build project
        run: cmake --build _build
        
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            artifacts
